export const defaultControlData = [
  {
    fieldLabel: "Section",
    internalName: "section",
    fieldType: "textbox",
    isFieldRequired: "No",
    isDefaultGenerated: true,
    valueSetBy: "MHK",
    validationPattern: "alphabetic",
    minCharLength: "",
    maxCharLength: "",
  },
  {
    fieldLabel: "Label",
    internalName: "label",
    fieldType: "textbox",
    isFieldRequired: "Yes",
    isDefaultGenerated: true,
    valueSetBy: "BOTH",
    validationPattern: "alphabetic",
    minCharLength: "",
    maxCharLength: "",
  },
  {
    fieldLabel: "Hidden",
    internalName: "hidden",
    fieldType: "select",
    isFieldRequired: "No",
    isDefaultGenerated: true,
    valueSetBy: "BOTH",
    options: [
      { key: 0, label: "Yes" },
      { key: 1, label: "No" },
    ],
  },
  {
    fieldLabel: "Mandatory",
    internalName: "mandatory",
    fieldType: "select",
    isFieldRequired: "Yes",
    isDefaultGenerated: true,
    valueSetBy: "BOTH",
    options: [
      { key: 0, label: "Yes" },
      { key: 1, label: "No" },
    ],
  },
  {
    fieldLabel: "Disabled",
    internalName: "disabled",
    fieldType: "select",
    isFieldRequired: "No",
    isDefaultGenerated: true,
    valueSetBy: "BOTH",
    options: [
      { key: 0, label: "Yes" },
      { key: 1, label: "No" },
    ],
  },
];
