export const VIEW_LIST_OF_CLIENTS = "VIEW_LIST_OF_CLIENTS";
export const ADD_CLIENT = "ADD_CLIENT";
export const VIEW_CLIENT_PROFILE = "VIEW_CLIENT_PROFILE";
export const UPDATE_CLIENT_PROFILE = "UPDATE_CLIENT_PROFILE";
export const TERM_CLIENT = "TERM_CLIENT";
// export const VIEW_CLIENT_HIERARCHY = "VIEW_CLIENT_HIERARCHY";
export const UPDATE_CLIENT_HIERARCHY = "UPDATE_CLIENT_HIERARCHY";
export const FIELD_SIGN_OFF_ACTION = "FIELD_SIGN_OFF_ACTION";
export const FIELD_APPROVE_ACTION = "FIELD_APPROVE_ACTION";
export const FIELD_RETRACT_ACTION = "FIELD_RETRACT_ACTION";
export const FIELD_REVIEW_ACTION = "FIELD_REVIEW_ACTION";
export const FIELD_MANUALLY_CONFIGURED_ACTION = "FIELD_MANUALLY_CONFIGURED_ACTION";
export const FIELD_QA_PASSFAIL_ACTION = "FIELD_QA_PASSFAIL_ACTION";
export const FIELD_RESTORE_OOB_ACTION = "FIELD_RESTORE_OOB_ACTION";
export const ADD_COMMENT_ON_CLIENT_FIELD = "ADD_COMMENT_ON_CLIENT_FIELD";
export const UPDATE_CLIENT_FIELD_ACTION = "UPDATE_CLIENT_FIELD_ACTION";
export const VIEW_CONFIGURATION_DEPLOYMENT = "VIEW_CONFIGURATION_DEPLOYMENT";
//export const CONFIGURATION_DEPLOYMENT_ACTION = "CONFIGURATION_DEPLOYMENT_ACTION";
export const VIEW_LETTERS = "VIEW_LETTERS";
export const LETTER_DEPLOYMENT_ACTION = "LETTER_DEPLOYMENT_ACTION";

export const VIEW_USER_LIST = "VIEW_USER_LIST";
export const VIEW_USER_PROFILE = "VIEW_USER_PROFILE";
export const ADD_USER = "ADD_USER";
export const TERMINATE_USER = "TERMINATE_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const VIEW_OWN_PROFILE = "VIEW_OWN_PROFILE";
export const UPDATE_OWN_PROFILE = "UPDATE_OWN_PROFILE";

export const VIEW_ROLE_PERMISSION = "VIEW_ROLE_PERMISSION";
export const UPDATE_ROLE_PERMISSION = "UPDATE_ROLE_PERMISSION";

export const VIEW_APP_SETTINGS = "VIEW_APP_SETTINGS";
export const ADD_ACTION_APP_SETTINGS = "ADD_ACTION_APP_SETTINGS";
export const UPDATE_ACTION_APP_SETTINGS = "UPDATE_ACTION_APP_SETTINGS";
export const DELETE_ACTION_APP_SETTINGS = "DELETE_ACTION_APP_SETTINGS";

export const VIEW_OOB_GLOBAL_CONFIG = "VIEW_OOB_GLOBAL_CONFIG";
export const ADD_ACTION_OOB_GLOBAL_CONFIG = "ADD_ACTION_OOB_GLOBAL_CONFIG";
export const UPDATE_ACTION_OOB_GLOBAL_CONFIG =
  "UPDATE_ACTION_OOB_GLOBAL_CONFIG";
export const DELETE_ACTION_OOB_GLOBAL_CONFIG =
  "DELETE_ACTION_OOB_GLOBAL_CONFIG";
export const VIEW_ADMIN_DASHBOARD = "VIEW_ADMIN_DASHBOARD";
