/**
 * API Urls Start
 */
export const CONTAINER_API_URL = process.env.CONTAINER_URL;
export const DOCUMENT_NAME = "document";

export const FETCH_BUSINESSLINE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/businessLines";
// export const FETCH_BUSINESSLINE_API_URL = 
//process.env.REACT_APP_API_DEV_URL + "/mhk/getBusinessLineList";

// export const FETCH_COMPANIES_API_URL =
//   process.env.REACT_APP_API_DEV_URL + "/mhk/getCompanyList";
export const FETCH_COMPANIES_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/companies";


export const FETCH_MODULES_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/modules";
export const ADD_FILE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports";
export const DELETE_FILE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports";
export const FETCH_ALLFILES_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports";
export const FETCH_STOPPED_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports/stopped";
export const DOWNLOAD_LETTER_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/download/";
export const FETCH_PROCESSING_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports/processing";
export const UPDATE_FILE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports";

export const TAG_INDICATORS_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/tag/indicators";

export const DOCTOHTML_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/"; // "/lat/tag/{id}/details"

export const HTMLTODOC_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/details";

export const LETTER_COMMENT_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/comment";

export const LETTER_LIRARY_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/library";

export const LETTER_AUDIT_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports/audit";

export const LETTER_TYPE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/type";

export const LETTER_MATRIX_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/stats/automation_matrix";

export const LETTER_LETTERSTATUS_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/stats/status_matrix";

export const LETTER_AUTVSINT_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/stats/automation_intervention";

export const LETTER_FETCHLOBS_BYCOMPID_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/imports/company/businessLines";

export const UPLOAD_FILE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/upload";
export const UPLOAD_MULTIFILE_API_URL =
  process.env.REACT_APP_API_DEV_URL + "/lat/letters/multiuplaod";

/**
 * API Urls End
 */
export const SHOW_SNACKBAR_ACTION = "SHOW_SNACKBAR_ACTION";

export const FETCH_BUSINESSLINE_COMPLETE = "FETCH_BUSINESSLINE_COMPLETE";
export const FETCH_BUSINESSLINE_FAILURE = "FETCH_BUSINESSLINE_FAILURE";

export const FETCH_MODULES_COMPLETE = "FETCH_MODULES_COMPLETE";
export const FETCH_MODULES_FAILURE = "FETCH_MODULES_FAILURE";

export const FETCH_COMPANY_COMPLETE = "FETCH_COMPANY_COMPLETE";
export const FETCH_COMPANY_FAILURE = "FETCH_COMPANY_FAILURE";

export const FETCH_ATTACHMENT_COMPLETE = "FETCH_ATTACHMENT_COMPLETE";
export const FETCH_ATTACHMENT_FAILURE = "FETCH_ATTACHMENT_FAILURE";

export const FETCH_COVERSHEET_COMPLETE = "FETCH_COVERSHEET_COMPLETE";
export const FETCH_COVERSHEET_FAILURE = "FETCH_COVERSHEET_FAILURE";

export const FETCH_ALLFILES_COMPLETE = "FETCH_ALLFILES_COMPLETE";
export const FETCH_ALLFILES_FAILURE = "FETCH_ALLFILES_FAILURE";
export const FETCH_ALLFILES_ERROR = "FETCH_ALLFILES_ERROR";

export const FETCH_FILE_COMPLETE = "FETCH_FILE_COMPLETE";
export const FETCH_FILE_FAILURE = "FETCH_FILE_FAILURE";
export const FETCH_FILE_ERROR = "FETCH_FILE_ERROR";

export const FETCH_STOPPED_COMPLETE = "FETCH_STOPPED_COMPLETE";
export const FETCH_STOPPED_FAILURE = "FETCH_STOPPED_FAILURE";
export const FETCH_STOPPED_ERROR = "FETCH_STOPPED_ERROR";

export const DOWNLOAD_LETTER_COMPLETE = "DOWNLOAD_LETTER_COMPLETE";
export const DOWNLOAD_LETTER_FAILURE = "DOWNLOAD_LETTER_FAILURE";
export const DOWNLOAD_LETTER_ERROR = "DOWNLOAD_LETTER_ERROR";

export const DOWNLOAD_LIBRARY_LETTER_COMPLETE = "DOWNLOAD_LIBRARY_LETTER_COMPLETE";
export const DOWNLOAD_LIBRARY_LETTER_FAILURE = "DOWNLOAD_LIBRARY_LETTER_FAILURE";
export const DOWNLOAD_LIBRARY_LETTER_ERROR = "DOWNLOAD_LIBRARY_LETTER_ERROR";

export const FETCH_PROCESSING_COMPLETE = "FETCH_PROCESSING_COMPLETE";
export const FETCH_PROCESSING_FAILURE = "FETCH_PROCESSING_FAILURE";
export const FETCH_PROCESSING_ERROR = "FETCH_PROCESSING_ERROR";

export const UPDATE_PROCESSING_COMPLETE = "UPDATE_PROCESSING_COMPLETE";
export const UPDATE_PROCESSING_FAILURE = "UPDATE_PROCESSING_FAILURE";
export const UPDATE_PROCESSING_ERROR = "UPDATE_PROCESSING_ERROR";

export const ADD_FILE_COMPLETE = "ADD_FILE_COMPLETE";
export const ADD_FILE_FAILURE = "ADD_FILE_FAILURE";
export const ADD_FILE_ERROR = "ADD_FILE_ERROR";
export const ADD_FILE_RESET = "ADD_FILE_RESET";

export const UPDATE_FILE_COMPLETE = "UPDATE_FILE_COMPLETE";
export const UPDATE_FILE_ERROR = "UPDATE_FILE_ERROR";
export const UPDATE_FILE_FAILURE = "UPDATE_FILE_FAILURE";

export const UPDATE_FILES_COMPLETE = "UPDATE_FILES_COMPLETE";
export const UPDATE_FILES_ERROR = "UPDATE_FILES_ERROR";
export const UPDATE_FILES_FAILURE = "UPDATE_FILES_FAILURE";

export const DELETE_FILE_COMPLETE = "DELETE_FILE_COMPLETE";
export const DELETE_FILE_ERROR = "DELETE_FILE_ERROR";
export const DELETE_FILE_FAILURE = "DELETE_FILE_FAILURE";

export const FETCH_INDICATORS_COMPLETE = "FETCH_INDICATORS_COMPLETE";
export const FETCH_INDICATORS_FAILURE = "FETCH_INDICATORS_FAILURE";
export const FETCH_INDICATORS_ERROR = "FETCH_INDICATORS_ERROR";

export const ADD_INDICATORS_COMPLETE = "ADD_INDICATORS_COMPLETE";
export const ADD_INDICATORS_FAILURE = "ADD_INDICATORS_FAILURE";
export const ADD_INDICATORS_ERROR = "ADD_INDICATORS_ERROR";

export const DELETE_INDICATORS_COMPLETE = "DELETE_INDICATORS_COMPLETE";
export const DELETE_INDICATORS_FAILURE = "DELETE_INDICATORS_FAILURE";
export const DELETE_INDICATORS_ERROR = "DELETE_INDICATORS_ERROR";

export const UPDATE_INDICATORS_COMPLETE = "UPDATE_INDICATORS_COMPLETE";
export const UPDATE_INDICATORS_FAILURE = "UPDATE_INDICATORS_FAILURE";
export const UPDATE_INDICATORS_ERROR = "UPDATE_INDICATORS_ERROR";

export const FETCH_INDIVIDUAL_INDICATORS_COMPLETE =
  "FETCH_INDIVIDUAL_INDICATORS_COMPLETE";
export const FETCH_INDIVIDUAL_INDICATORS_ERROR =
  "FETCH_INDIVIDUAL_INDICATORS_ERROR";
export const FETCH_INDIVIDUAL_INDICATORS_FAILURE =
  "FETCH_INDIVIDUAL_INDICATORS_FAILURE";

export const FETCH_INDICATORBYID_COMPLETE = "FETCH_INDICATORBYID_COMPLETE";
export const FETCH_INDICATORBYID_FAILURE = "FETCH_INDICATORBYID_FAILURE";

export const FETCH_LETTERHTML_COMPLETE = "FETCH_LETTERHTML_COMPLETE";
export const FETCH_LETTERHTML_FAILURE = "FETCH_LETTERHTML_FAILURE";
export const FETCH_LETTERHTML_ERROR = "FETCH_LETTERHTML_ERROR";

export const FETCH_REVERTHTML_COMPLETE = "FETCH_REVERTHTML_COMPLETE";
export const FETCH_REVERTHTML_FAILURE = "FETCH_REVERTHTML_FAILURE";
export const FETCH_REVERTHTML_ERROR = "FETCH_REVERTHTML_ERROR";

export const UPDATE_LETTERDOC_COMPLETE = "UPDATE_LETTERDOC_COMPLETE";
export const UPDATE_LETTERDOC_FAILURE = "UPDATE_LETTERDOC_FAILURE";
export const UPDATE_LETTERDOC_ERROR = "UPDATE_LETTERDOC_ERROR";

export const SAVE_COMMENTS_COMPLETE = "SAVE_COMMENTS_COMPLETE";
export const SAVE_COMMENTS_FAILURE = "SAVE_COMMENTS_FAILURE";
export const SAVE_COMMENTS_ERROR = "SAVE_COMMENTS_ERROR";

export const FETCH_LIBRARY_COMPLETE = "FETCH_LIBRARY_COMPLETE";
export const FETCH_LIBRARY_FAILURE = "FETCH_LIBRARY_FAILURE";
export const FETCH_LIBRARY_ERROR = "FETCH_LIBRARY_ERROR";

export const FETCH_AUDIT_COMPLETE = "FETCH_AUDIT_COMPLETE";
export const FETCH_AUDIT_FAILURE = "FETCH_AUDIT_FAILURE";
export const RESET_AUDIT = "RESET_AUDIT";

export const FETCH_METRICS_COMPLETE = "FETCH_METRICS_COMPLETE";
export const FETCH_METRICS_FAILURE = "FETCH_METRICS_FAILURE";
export const FETCH_METRICS_ERROR = "FETCH_METRICS_ERROR";

export const FETCH_LETTERSTATUS_COMPLETE = "FETCH_LETTERSTATUS_COMPLETE";
export const FETCH_LETTERSTATUS_FAILURE = "FETCH_LETTERSTATUS_FAILURE";
export const FETCH_LETTERSTATUS_ERROR = "FETCH_LETTERSTATUS_ERROR";

export const FETCH_AUTVSINT_COMPLETE = "FETCH_AUTVSINT_COMPLETE";
export const FETCH_AUTVSINT_FAILURE = "FETCH_AUTVSINT_FAILURE";
export const FETCH_AUTVSINT_ERROR = "FETCH_AUTVSINT_ERROR";

export const SAVE_FILE_COMPLETE = "SAVE_FILE_COMPLETE";

export const RESET_LETTERHTML = "RESET_LETTERHTML";
export const RESET_LETTERAUDIT_IS_DONE = "RESET_LETTERAUDIT_IS_DONE";
export const RESET_LETTERDATE_IS_DONE = "RESET_LETTERDATE_IS_DONE";

export const FETCH_LOBBYCOMPID_COMPLETE = "FETCH_LOBBYCOMPID_COMPLETE";
export const FETCH_LOBBYCOMPID_FAILURE = "FETCH_LOBBYCOMPID_FAILURE";
export const UPDATE_PROCESSING_STATUS = "UPDATE_PROCESSING_STATUS";

export const UPLOAD_FILE_COMPLETE = "UPLOAD_FILE_COMPLETE";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_START_INDEX = 0;
export const SET_DEFAULT_STARTINDEX = "SET_DEFAULT_STARTINDEX";
export const DEFAULT_SORTBY = "id";
export const SEARCH = "LIBRARY";
export const FILTERBY = "search";
export const RESET_INVALIDTAG = "RESET_INVALIDTAG";
export const RESET_LETTERUPDATE = "RESET_LETTERUPDATE";

